webtalk_init -webtalk_dir E:/Faculty of Engineering, Ain Shams University/3rd CSE 2018 - 2019/Lectures/Computer Organization/Project/PPI/CO2018PPI/PPI/PPI.sim/sim_1/behav/xsim/xsim.dir/PortA_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Nov 28 11:05:21 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "c145de35-c715-4098-a6d5-7ab2e73f7b72" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "f7fdbc4e9d514638b374134c0fb77749" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "12" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2594 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.08_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "5556_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1318890095 -regid "" -xml E:/Faculty of Engineering, Ain Shams University/3rd CSE 2018 - 2019/Lectures/Computer Organization/Project/PPI/CO2018PPI/PPI/PPI.sim/sim_1/behav/xsim/xsim.dir/PortA_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/Faculty of Engineering, Ain Shams University/3rd CSE 2018 - 2019/Lectures/Computer Organization/Project/PPI/CO2018PPI/PPI/PPI.sim/sim_1/behav/xsim/xsim.dir/PortA_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/Faculty of Engineering, Ain Shams University/3rd CSE 2018 - 2019/Lectures/Computer Organization/Project/PPI/CO2018PPI/PPI/PPI.sim/sim_1/behav/xsim/xsim.dir/PortA_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
